EasyMeal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

urlpatterns = [
    path('easymeal/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('easyapi/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('easyapi/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('easyapi/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('api-auth/', include('rest_framework.urls')),
    path('easyapi/', include('EasyMeal.apiurls')),
    path('blog/', include('blog.urls')),
    path('restaurant/', include('restaurant.urls')),
    path("firebase-messaging-sw.js", TemplateView.as_view(template_name="js/firebase-messaging-sw.js", content_type="application/javascript")),
    path("", include('home.urls'))
    # path("", TemplateView.as_view(template_name="indexT.html")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.site_header = 'Easy Meal'
admin.site.site_title = 'Easy Meal'
admin.site.index_title = "Welcome to Easy Meal"

blog/urls.py
from django.urls import path
from . import views
app_name = "blog"
urlpatterns = [
        path('<slug:slug>/add_comment/', views.add_comment, name='add_comment'),
        path('service/', views.services, name='service'),
        path('subscribe/', views.subscribe, name='subscribe'),
        path('<slug:slug>/', views.blogDetails, name='blog_detail'),
        path('', views.blog, name='blog_page'),
]

home/urls.py
from django.urls import path
from . import views
app_name="home"
urlpatterns = [
        path('<slug:slug>/submit-feedback/', views.submit_feedback, name='submit_feedback'),
        path('ajax/fcm-token/',views.fcm_token,name='fcm_token'),
        path('ajax/update_dtype/',views.update_dtype,name='update_dtype'),
        path('faq/message/', views.faq_message, name='faq_message'),
        path('about/',views.about,name='about-page'),
        path('faq/',views.faq,name='faq'),
        path('pricing-table/',views.pricingTable,name='pricing-table'),
        path('contact/',views.contact,name='contact'),
        path('checkout/',views.checkout,name='checkout'),
        path('become-partner/',views.becomePartner,name='become-partner'),
        path('page-not-found/', views.notfound,name='page-not-found'),
        path('myorder/',views.myorder,name='myorder'),
        path('register/',views.register,name='register'),
        path('login/', views.login, name='login'),
        path("notify/", views.index, name="index"),
        path('logout/', views.user_logout, name='logout'),
        path('forgot-password/', views.forgot_password, name='forgot_password'),
        path('verify-otp/<int:user_id>/', views.verify_otp, name='verify_otp'),
        path('reset-password/<int:user_id>/', views.reset_password, name='reset_password'),
        path('order/<str:identifier>/', views.singelOrder, name='singelOrder'),
        path('<slug:slug>/submit-feedback/', views.submit_feedback, name='submit_feedback'),
        path('profile/', views.profile, name='profile'),
        path('change-password/', views.change_password, name='change_password'),
        path('update_user_address/', views.update_user_address, name='update_user_address'),
        path('<str:slug>/', views.page_detail, name='page_detail'),
        path('', views.home, name='home-page'),   
]

restaurant/urls.py
from django.urls import path
from . import views
app_name = "restaurant"
urlpatterns = [
	path('ajax/<slug:restro>/food-items/<slug:slug>/edit/', views.edit_food_item, name='edit_food_item'),
	path('ajax/<slug:restro>/food-items/<slug:slug>/delete/', views.delete_food_item, name='delete_food_item'),
	path('ajax/<slug:restro>/food-items/create/', views.create_food_item, name='create_food_item'),
    path('ajax/add-to-cart/', views.add_to_cart, name='add_to_cart'),
    path('ajax/clear_cart/', views.clear_cart, name='clear_cart'),
    path('ajax/update_order_type/', views.update_order_type, name='update_order_type'),
	path('my-restaurant/<slug:restro>/food-items/', views.food_items, name='food_items'),
	path('my-restaurant/<slug:restro>/orders/', views.orders_items, name='orders_items'),
	path('cuisine/<slug:cuisine_slug>/', views.restaurant, name='restaurants-cuisine'),
	path('<slug:slug>/<str:category>/', views.restaurantCard, name='restaurant-card-category'),
    path('validate-voucher/', views.validate_voucher, name='validate_voucher'),
	path('my-restaurant', views.myRestaurant, name='my_restaurant'),
	path('add-restaurant', views.addRestaurant, name='add_restaurant'),
	path('<slug:slug>/', views.restaurantCard, name='restaurant-card'),
	path('', views.restaurant, name='restaurant'),
]

blog/models.py
from django.db import models
from datetime import timedelta, date
from ckeditor_uploader.fields import RichTextUploadingField
from django_extensions.db.fields import AutoSlugField
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils.html import strip_tags
from firebase_admin.messaging import Message, Notification
from fcm_django.models import FCMDevice
from home.models import User, trackupdate, save_notifications, BaseModel, settings

# Create your models here.

status = (("Draft","Draft"),("Schedule","Schedule"),("Active","Active"),("Inactive","Inactive"),("Delete","Delete"))

class Category(BaseModel):
	"""docstring for Category"""
	category = models.ForeignKey("self", on_delete=models.PROTECT, related_name="category_name", blank=True,null=True)
	title = models.CharField(max_length=160)
	slug = AutoSlugField(max_length=160, populate_from=['title'], unique=True, editable=True)
	content = RichTextUploadingField()
	posts = models.PositiveIntegerField(default=0)
	words = models.PositiveIntegerField(default=0)
	new_words = models.PositiveIntegerField(default=0)
	keyword = models.CharField(max_length=160)
	meta_title = models.CharField(max_length=160)
	meta_description = models.TextField()
	thumbnail = models.ImageField(upload_to='blog/category/thumbnail', blank=True)	
	cover = models.ImageField(upload_to='blog/category/cover', blank=True)

	class Meta:
		verbose_name_plural = '01. Categories'
	
	def __str__(self):
		return (self.title)

	def save(self, *args, **kwargs):
		trackupdate(self)
		word_count=strip_tags(self.content).replace('&nbsp;',' ').strip().split()
		newwords=len(word_count)
		counts=newwords-self.words
		self.words=newwords
		self.new_words=counts
		return super().save(*args, **kwargs)

class Tag(BaseModel):
	"""docstring for Tag"""
	title = models.CharField(max_length=160)
	slug = AutoSlugField(max_length=160, populate_from=['title'], unique=True, editable=True)
	content = RichTextUploadingField()
	posts = models.PositiveIntegerField(default=0)
	words = models.PositiveIntegerField(default=0)
	new_words = models.PositiveIntegerField(default=0)
	keyword = models.CharField(max_length=160)
	meta_title = models.CharField(max_length=160)
	meta_description = models.TextField()

	class Meta:
		verbose_name_plural = '02. Tags'

	def __str__(self):
		return (self.title)

	def save(self, *args, **kwargs):
		trackupdate(self)
		word_count=strip_tags(self.content).replace('&nbsp;',' ').strip().split()
		newwords=len(word_count)
		counts=newwords-self.words
		self.words=newwords
		self.new_words=counts
		return super().save(*args, **kwargs)
		
class Post(models.Model):
	"""docstring for Post"""
	author = models.ForeignKey(User, on_delete=models.CASCADE)
	category = models.ForeignKey(Category, on_delete=models.CASCADE)
	tag = models.ManyToManyField(Tag)
	# like = models.ManyToManyField(User, related_name='post_like',blank=True)
	# unlike = models.ManyToManyField(User, related_name='post_unlike',blank=True)
	# favourite = models.ManyToManyField(User, related_name='post_favourite')
	title = models.CharField(max_length=160)
	slug = AutoSlugField(max_length=160, populate_from=['title'], unique=True, editable=True)
	content = RichTextUploadingField()
	words = models.PositiveIntegerField(default=0)
	new_words = models.PositiveIntegerField(default=0)
	keyword = models.CharField(max_length=160)
	meta_title = models.CharField(max_length=160)
	meta_description = models.TextField()
	thumbnail = models.ImageField(upload_to='blog/thumbnail')
	featured = models.ImageField(upload_to='blog/image')
	view = models.PositiveIntegerField(default=0)
	bookmark = models.PositiveIntegerField(default=0)
	impression = models.PositiveIntegerField(default=0)
	timestamp = models.DateTimeField(auto_now_add=True, editable=False)
	utimestamp = models.DateTimeField(auto_now=True, editable=False)
	track = models.TextField(blank=True, editable=False)
	utrack = models.TextField(blank=True, editable=False)
	locate = models.TextField(blank=True)
	status = models.CharField(max_length=20, choices=status, default='Draft')

	class Meta:
		verbose_name_plural = '03. Posts'

	def __str__(self):
		return (self.title)

	def comments(self):
		yesterday = date.today() + timedelta(days=-1)
		return Comment.objects.filter(post = self.id, parent=None, status='Active').order_by('-id') | Comment.objects.filter(post = self.id, parent=None, timestamp__gte=yesterday).order_by('-id')

	def comment_count(self):
		return Comment.objects.filter(post = self.id).count()

	def save(self, *args, **kwargs):
		trackupdate(self)
		word_count=strip_tags(self.content).replace('&nbsp;',' ').strip().split()
		newwords=len(word_count)
		counts=newwords-self.words
		self.words=newwords
		self.new_words=counts
		super(Post, self).save(*args, **kwargs)
		posts = Post.objects.all()
		cposts = posts.filter(category=self.category).count()
		self.category.posts = cposts
		self.category.save()
		for i in self.tag.all():
			tposts = Post.objects.filter(tag=i).count()
			i.posts = tposts
			i.save()
		data = {'type': "Post",'id':str(self.id), 'slug':str(self.slug)}
		title="New blog post added! Check it out now."
		body="New blog post added! Check it out now."
		users = User.objects.filter(notification=True).exclude(id=self.author.id).values_list("id", flat=True)
		FCMDevice.objects.filter(user__in=users).send_message(
			Message(notification=Notification(title=title, body=body, image=settings.EASYLOGO),data=data)
		)
		save_notifications(title,body,ntype='Post', slug=str(self.slug), user=self.author)

class Action(BaseModel):
	post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='action_post')
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='action_user')
	share = models.PositiveIntegerField(default=0)
	like = models.BooleanField(default=False)
	unlike = models.BooleanField(default=False)
	favourite = models.BooleanField(default=False)

	class Meta:
		verbose_name_plural = '04. Actions'

	def __str__(self):
		return str(self.post)
	
	def save(self, *args, **kwargs):
		trackupdate(self)
		if self.like:
			self.unlike = False
		if self.unlike:
			self.like = False
		super(Action, self).save(*args, **kwargs)

class Comment(models.Model):
	"""docstring for Comment"""
	parent = models.ForeignKey("self", on_delete=models.PROTECT, blank=True, null=True)
	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
	name = models.CharField(max_length=30)
	email = models.EmailField(verbose_name='Email')
	website = models.URLField(blank=True)
	mobile 	= models.BigIntegerField(validators=[MinValueValidator(5000000000),MaxValueValidator(999999999999)])
	content = models.TextField()
	notify = models.BooleanField(default=False)
	pin = models.BooleanField(default=False)
	timestamp = models.DateTimeField(auto_now_add=True)
	utimestamp = models.DateTimeField(auto_now=True)
	track = models.TextField(blank=True, editable=False)
	utrack = models.TextField(blank=True, editable=False)
	locate = models.TextField(blank=True)
	status = models.CharField(max_length=20, choices=status, default='Inactive')

	class Meta:
		verbose_name_plural = '05. Comments'

	def __str__(self):
		return (self.name)

	def reply(self):
		return Comment.objects.filter(parent = self.id, status='Active').all()
	
	def save(self, *args, **kwargs):
		trackupdate(self)
		super(Comment, self).save(*args, **kwargs)

class Badword(BaseModel):
	"""docstring for Badword"""
	title = models.CharField(max_length=20, unique=True)
	count = models.PositiveIntegerField(default=0)

	class Meta:
		verbose_name_plural = '06. Badwords'

	def __str__(self):
		return self.title
	
	def save(self, *args, **kwargs):
		trackupdate(self)
		super(Badword, self).save(*args, **kwargs)
		
class Subscribe(BaseModel):
	"""docstring for Subscribe"""
	user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
	email = models.EmailField(verbose_name='Email')
	mobile = models.CharField(max_length=10)
	name = models.CharField(max_length=100)
	url = models.URLField(max_length=100)

	class Meta:
		verbose_name_plural = '07. Subscribe'

	def save(self, *args, **kwargs):
		super().save(*args, **kwargs)
		if self.user and self.user.notification:
			device = FCMDevice.objects.filter(user=self.user)
			data = {'type': "Subscribed_Id", 'id': str(self.id)} if self.id else {'type': "Subscribed"}
			if device:
				device.send_message(
					Message(notification=Notification(title="Subscribed", body="Subscribed Successfully", image=settings.EASYLOGO), data=data)
				)

geolocation/models.py
from django.db import models

# Create your models here.

status = (("Active","Active"), ("Inactive","Inactive"), ("Delete","Delete"))
pattern = (("LR","Left to Right"), ("RL","Right to Left"), ("TB","Top to Bottom"), ("BT","Bottom to Top"))

class Language(models.Model):
	code = models.CharField(max_length=5)
	name = models.CharField(max_length=25)
	pattern = models.CharField(max_length=2, choices=pattern, default='LR')
	track = models.TextField(blank=True, editable=False)
	timestamp = models.DateTimeField(auto_now_add=True, editable=False)
	status = models.CharField(max_length=10, choices=status, default='Active')

	def __str__(self):
		return self.name
	
	class Meta:
		verbose_name_plural = '01. Languages'

class Continent(models.Model):
	name = models.CharField(max_length=50)
	area = models.BigIntegerField()
	population = models.BigIntegerField()
	track = models.TextField(blank=True, editable=False)
	timestamp = models.DateTimeField(auto_now_add=True, editable=False)
	status = models.CharField(max_length=10, choices=status, default='Active')

	def __str__(self):
		return self.name
	
	class Meta:
		verbose_name_plural = '02. Continents'

class Country(models.Model):
	continent = models.ForeignKey(Continent, on_delete=models.PROTECT)
	name = models.CharField(max_length=50)
	local = models.CharField(max_length=50)
	code = models.IntegerField()
	code2 = models.CharField(max_length=2)
	code3 = models.CharField(max_length=3)
	capital = models.CharField(max_length=50)
	gdp = models.BigIntegerField()
	area = models.BigIntegerField()
	population = models.BigIntegerField()
	latitude = models.FloatField()
	longitude = models.FloatField()
	track = models.TextField(blank=True, editable=False)
	timestamp = models.DateTimeField(auto_now_add=True, editable=False)
	status = models.CharField(max_length=10, choices=status, default='Active')

	class Meta:
		verbose_name_plural = "03. Countries"

	def __str__(self):
		return self.name

class State(models.Model):
	country = models.ForeignKey(Country, on_delete=models.PROTECT)
	name = models.CharField(max_length=50)
	local = models.CharField(max_length=50)
	capital = models.CharField(max_length=50)
	area = models.BigIntegerField()
	population = models.BigIntegerField()
	latitude = models.FloatField()
	longitude = models.FloatField()
	track = models.TextField(blank=True, editable=False)
	timestamp = models.DateTimeField(auto_now_add=True, editable=False)
	status = models.CharField(max_length=10, choices=status, default='Active')

	def __str__(self):
		return str(self.country.name)+" | "+str(self.name)
	
	class Meta:
		verbose_name_plural = "04. States"

class Timezone(models.Model):
	"""docstring for Timezone"""
	country = models.ForeignKey(Country, on_delete=models.PROTECT)
	time = models.TimeField()
	negative = models.BooleanField(default=False)
	name = models.CharField(max_length=50, blank=True, help_text="IST")
	display = models.CharField(max_length=30, help_text="Asia/Kolkata")
	utc = models.CharField(max_length=10, help_text="UTC+5:30")
	city = models.CharField(max_length=50)
	track = models.TextField(blank=True, editable=False)
	timestamp = models.DateTimeField(auto_now_add=True, editable=False)
	status = models.CharField(max_length=10, choices=status, default='Active')

	def __str__(self):
		return str(self.country)+' | '+str(self.utc)
	
	class Meta:
		verbose_name_plural = "05. Timezones"

home/templates/ui/add-restaurant.html
{% extends "index.html" %}
{% load custom_filter %}
{% load static %}
{% block content %}
<style>
    h1 {
        text-align: center;
        margin-bottom: 30px;
    }
    
    .form-group {
        margin-bottom: 20px;
    }
    
    label {
        display: block;
        margin-bottom: 5px;
        font-weight: bold;
    }
    
    .form-control,
    .form-control-file,
    .form-check-input {
        width: 100%;
        padding: 10px;
        border: 1px solid #ced4da;
        border-radius: 4px;
        font-size: 14px;
    }
    
    .form-control-file {
        padding: 0;
    }
    
    .form-control:focus {
        border-color: #80bdff;
        outline: 0;
        box-shadow: 0 0 5px rgba(0, 123, 255, 0.25);
    }
    
    .form-check-input {
        width: auto;
        margin-right: 10px;
    }
</style>

<div class="menu-layer ">	
    <section class="hero-section about gap">
        <div class="container">
            
        </div>
	</section>
	<!-- banner -->
	<section class="banner mb-5" data-aos="fade-up"  data-aos-delay="200" data-aos-duration="300">
		<div class="container">
			
		</div>
	</section>
	<section class="best-restaurants gap">
		<div class="container">
			<div class="row mx-0">
                <div class="container">
                    <h1>Create a New Restaurant</h1>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        
                        <div class="form-group">
                            <label for="id_title">Title:</label>
                            {{ form.title|add_class:"form-control" }}
                        </div>
                        
                        <div class="form-group">
                            <label for="id_logo">Logo:</label>
                            {{ form.logo|add_class:"form-control-file" }}
                        </div>
                        
                        <div class="form-group">
                            <label for="id_image">Image:</label>
                            {{ form.image|add_class:"form-control-file" }}
                        </div>
            
                        <div class="form-group">
                            <label for="id_phone">Phone:</label>
                            {{ form.phone|add_class:"form-control" }}
                        </div>
                        
                        <div class="form-group">
                            <label for="id_email">Email:</label>
                            {{ form.email|add_class:"form-control" }}
                        </div>
            
                        <div class="form-group">
                            <label for="id_found">Found:</label>
                            <input type="date" name="found" id="id_found" class="form-control">
                        </div>
            
                        <div class="form-group">
                            <label for="id_city">City:</label>
                            {{ form.city|add_class:"form-control" }}
                        </div>
            
                        <div class="form-group">
                            <label for="id_postcode">Postcode:</label>
                            {{ form.postcode|add_class:"form-control" }}
                        </div>
            
                        <div class="form-group">
                            <label for="id_address">Address:</label>
                            {{ form.address|add_class:"form-control" }}
                        </div>
            
                        <div class="form-group">
                            <label for="id_latitude">Latitude:</label>
                            {{ form.latitude|add_class:"form-control" }}
                        </div>
            
                        <div class="form-group">
                            <label for="id_longitude">Longitude:</label>
                            {{ form.longitude|add_class:"form-control" }}
                        </div>
            
                        <div class="form-group">
                            <label for="id_website">Website:</label>
                            {{ form.website|add_class:"form-control" }}
                        </div>
            
                        <div class="form-group">
                            <label for="id_facebook">Facebook:</label>
                            {{ form.facebook|add_class:"form-control" }}
                        </div>
            
                        <div class="form-group">
                            <label for="id_twitter">Twitter:</label>
                            {{ form.twitter|add_class:"form-control" }}
                        </div>
            
                        <div class="form-group">
                            <label for="id_instagram">Instagram:</label>
                            {{ form.instagram|add_class:"form-control" }}
                        </div>
            
                        <div class="form-group">
                            <label for="id_linkedin">LinkedIn:</label>
                            {{ form.linkedin|add_class:"form-control" }}
                        </div>
        
            
                        <button type="submit" class="button-price">Save</button>
                    </form>
                </div>
			</div>
		</div>
	</section>
  <div class="bsl-popup" data-theme="quickeat" data-category="html">
    <div class="bsl-popup__buttons"></div>
    <div class="bsl-popup__content bsl-popup__content-related">
      <div class="bsl-popup__menu"></div>
      <div class="bsl-popup__tabs">
        <div class="bsl-popup__tab bsl-popup__tab-demo"></div>
        <div class="bsl-popup__tab bsl-popup__tab-all"></div>
        <div class="bsl-popup__tab bsl-popup__tab-related"></div>
        <div class="bsl-popup__tab bsl-popup__tab-version"></div>
      </div>
    </div>
    <div class="bsl-popup__content bsl-popup__content-help"></div>
  </div>
</div>
{% endblock %}

home/templates/ui/contact.html
{% extends "index.html" %} {% load static %} {% block content %}

<div class="menu-layer">
	<!-- loader start-->
	<div class="page-loader">
		<div class="wrapper">
	        <div class="circle"></div>
	        <div class="circle"></div>
	        <div class="circle"></div>
	        <div class="shadow"></div>
	        <div class="shadow"></div>
	        <div class="shadow"></div>
	        <span>Loading</span>
	    </div>
	</div>
	<!-- loader end-->
  <!-- hero-section -->
  <section class="hero-section about gap">
		<div class="container pt-2">
				<div class="row align-items-center mx-0">
					<div class="col-xl-6 col-lg-12" data-aos="fade-up"  data-aos-delay="200" data-aos-duration="300">
						<div class="about-text">
							<ul class="crumbs d-flex">
								<li><a href="{% url "home:home-page" %}">Home</a></li>
								<li class="two"><a href="{% url "home:contact" %}"><i class="fa-solid fa-right-long"></i>Contacts</a></li>
							</ul>
							<h2>Contact Us</h2>
							<p>Have a query? Contact us below:</p>
						</div>
						<div class="row mx-0">
							<div class="col-lg-4 col-md-4 col-sm-12">
								<div class="address">
									<i class="fa-solid fa-location-dot"></i>
									<h5>Gulf Harbour Whangaparāoa 0930</h5>
								</div>
							</div>
							<div class="col-lg-4 col-md-4 col-sm-12">
								<div class="address">
									<i class="fa-solid fa-envelope"></i>
									<a href="mailto:ordereasynz1@gmail.com"><h6>ordereasynz1@gmail.com</h6></a>
									<!-- <span>Dolore magna aliqua</span> -->
								</div>
							</div>
							<div class="col-lg-4 col-md-4 col-sm-12">
								<div class="address">
									<i class="fa-solid fa-phone"></i>
									<a href="callto:020 40007241"><h6>+64212477475</h6></a>
									<span>Call our support team</span>
								</div>
							</div>
						</div>
					</div>
					<div class="col-xl-6 col-lg-12" data-aos="fade-up"  data-aos-delay="300" data-aos-duration="400">
					<div class="contact-us-img">
						<img alt="contacts-img-girl" src="https://bslthemes.com/html/quickeat/assets/img/contacts-1.png" class="w-100">
					</div>

				</div>
				</div>
		</div>
  </section>
  <!-- contact map -->
  <section class="gap no-top">
  	<div class="container">
  		<div class="row mx-0">
  			<div class="col-lg-12" data-aos="fade-up"  data-aos-delay="300" data-aos-duration="400">
  				<div class="contact-map-data">
						<div class="join-courier content">
							<h3>Get in touch with us</h3>
							<p>Magna sit amet purus gravida quis blandit turpis cursus. Venenatis tellus in metus vulputate eu scelerisque felis.</p>
							<form class="blog-form">
								<div class="name-form">
									<i class="fa-regular fa-user"></i>
									<input type="text" name="name" placeholder="Enter your name">
								</div>
								<div class="name-form">
									<i class="fa-regular fa-envelope"></i>
									<input type="text" name="email" placeholder="Enter your email">
								</div>
								<textarea placeholder="Enter your message"></textarea>
								<button class="button-price">Submit Application</button>
							</form>

						</div>
						<div class="contact-map">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2689446.104646556!2d28.705460424349365!3d48.83127549941125!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40d1d9c154700e8f%3A0x1068488f64010!2sUkraine!5e0!3m2!1sen!2s!4v1661009847728!5m2!1sen!2s" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>

            </div>
          </div>
				</div>
  		</div>
  	</div>
  </section>
  <!-- subscribe-section -->
	<!-- <section class="subscribe-section gap" style="background:#fcfcfc">
		<div class="container">
			<div class="row align-items-center mx-0">
				<div class="col-lg-6" data-aos="flip-up"  data-aos-delay="200" data-aos-duration="300">
					<div class="img-subscribe">
						<img alt="Illustration"  src="https://bslthemes.com/html/quickeat/assets/img/illustration-4.png" class="w-100">
					</div>
				</div>
				<div class="col-lg-5 offset-lg-1" data-aos="flip-up"  data-aos-delay="300" data-aos-duration="400">
					<div class="get-the-menu">
						<h2>Get the menu of your favorite restaurants every day</h2>
						<form>
							<i class="fa-regular fa-bell"></i>
							<input type="text" name="email" placeholder="Enter email address">
							<button class="button button-2">Subscribe</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</section> -->
	
  

  <!-- bslthemes.com buttons html begin -->
  <div class="bsl-popup" data-theme="quickeat" data-category="html">
    <div class="bsl-popup__buttons"></div>
    <div class="bsl-popup__content bsl-popup__content-related">
      <div class="bsl-popup__menu"></div>
      <div class="bsl-popup__tabs">
        <div class="bsl-popup__tab bsl-popup__tab-demo"></div>
        <div class="bsl-popup__tab bsl-popup__tab-all"></div>
        <div class="bsl-popup__tab bsl-popup__tab-related"></div>
        <div class="bsl-popup__tab bsl-popup__tab-version"></div>
      </div>
    </div>
    <div class="bsl-popup__content bsl-popup__content-help"></div>
  </div>
  <!-- bslthemes.com buttons html end -->
  <!-- bslthemes.com buttons assets end -->
</div>
{% endblock %}

home/templates/ui/verify_otp.html
{% extends "index.html" %}
{% block content %}


<section class="verify-otp-section">
    <div class="verify-otp-container">
        <h2>Verify OTP</h2>
        {% if error_message %}
            <p class="text-danger">{{ error_message }}</p>
        {% endif %}
        <form method="post" action="{% url 'home:verify_otp' user_id=user.id %}">
            {% csrf_token %}
            <div class="verify-otp-form-group">
                <label for="otp">OTP</label>
                <input type="text" id="otp" name="otp" class="form-control" required>
            </div>
            <button type="submit" class="btn btn-verify-otp">Verify OTP</button>
        </form>
    </div>
</section>
{% endblock %}